"Key(W)" = "HardDrop"
"Key(S)" = "SoftDrop"
"Key(A)" = "Left"
"Key(D)" = "Right"
"Key(L)" = "RotateCW"
"Key(K)" = "Rotate180"
"Key(J)" = "RotateCCW"
"Key(Left Shift)" = "Hold"

"Btn(dpup)" = "HardDrop"
"Btn(dpdown)" = "SoftDrop"
"Btn(dpleft)" = "Left"
"Btn(dpright)" = "Right"
"Btn(b)" = "RotateCW"
"Btn(y)" = "Rotate180"
"Btn(a)" = "RotateCCW"
"Btn(leftshoulder)" = "Hold"
