# Pieces are defined as lists of pairs of [row, column] coordinates representing 
# blocks that are filled in, relative to the top left corner.
# There are 4 coordinate lists per piece, one for each rotation.

# Valid colors:
    # Cyan
    # Magenta
    # Yellow
    # Blue
    # Orange
    # Green
    # Red
    # Gray

[I]
shape = [
    [[1, 0], [1, 1], [1, 2], [1, 3]], # Initial Rotation
    [[0, 2], [1, 2], [2, 2], [3, 2]], # Clockwise
    [[2, 0], [2, 1], [2, 2], [2, 3]], # 180
    [[0, 1], [1, 1], [2, 1], [3, 1]], # Counterclockwise
]
color = "Cyan"
kick_table = "SRS_I"

[T]
shape = [
    [[0, 1], [1, 0], [1, 1], [1, 2]],
    [[0, 1], [1, 1], [1, 2], [2, 1]],
    [[1, 0], [1, 1], [1, 2], [2, 1]],
    [[0, 1], [1, 0], [1, 1], [2, 1]],
]
color = "Magenta"
kick_table = "SRS"

[O]
shape = [
    [[0, 1], [0, 2], [1, 1], [1, 2]],
    [[0, 1], [0, 2], [1, 1], [1, 2]],
    [[0, 1], [0, 2], [1, 1], [1, 2]],
    [[0, 1], [0, 2], [1, 1], [1, 2]],
]
color = "Yellow"
kick_table = "SRS"

[J]
shape = [
    [[0, 0], [1, 0], [1, 1], [1, 2]],
    [[0, 1], [0, 2], [1, 1], [2, 1]],
    [[1, 0], [1, 1], [1, 2], [2, 2]],
    [[0, 1], [1, 1], [2, 0], [2, 1]],
]
color = "Blue"
kick_table = "SRS"

[L]
shape = [
    [[0, 2], [1, 0], [1, 1], [1, 2]],
    [[0, 1], [1, 1], [2, 1], [2, 2]],
    [[1, 0], [1, 1], [1, 2], [2, 0]],
    [[0, 0], [0, 1], [1, 1], [2, 1]],
]
color = "Orange"
kick_table = "SRS"

[S]
shape = [
    [[0, 1], [0, 2], [1, 0], [1, 1]],
    [[0, 1], [1, 1], [1, 2], [2, 2]],
    [[1, 1], [1, 2], [2, 0], [2, 1]],
    [[0, 0], [1, 0], [1, 1], [2, 1]],
]
color = "Green"
kick_table = "SRS"

[Z]
shape = [
    [[0, 0], [0, 1], [1, 1], [1, 2]],
    [[0, 2], [1, 1], [1, 2], [2, 1]],
    [[1, 0], [1, 1], [2, 1], [2, 2]],
    [[0, 1], [1, 0], [1, 1], [2, 0]],
]
color = "Red"
kick_table = "SRS"

[2]
shape = [
    [[0, 1], [0, 2]],
    [[0, 2], [1, 2]],
    [[1, 1], [1, 2]],
    [[0, 1], [1, 1]],
]
color = "Gray"
kick_table = "SRS"

[X]
shape = [
    [[0, 1], [1, 0], [1, 1], [1, 2], [2, 1]],
    [[0, 2], [1, 2], [2, 2], [3, 2], [4, 2]],
    [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]],
    [[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]],
]
color = "Gray"
kick_table = "SRS_I"
