# Pieces are defined as lists of pairs of [column, row] coordinates representing
# blocks that are filled in, relative to the top left corner.
# There are 4 coordinate lists per piece, one for each rotation.

# Valid colors:
    # Cyan
    # Magenta
    # Yellow
    # Blue
    # Orange
    # Green
    # Red
    # Gray

[I]
shape = [
    [[0, 1], [1, 1], [2, 1], [3, 1]], # Initial Rotation
    [[2, 0], [2, 1], [2, 2], [2, 3]], # Clockwise
    [[0, 2], [1, 2], [2, 2], [3, 2]], # 180
    [[1, 0], [1, 1], [1, 2], [1, 3]], # Counterclockwise
]
color = "Cyan"
kick_table = "SRS_I"
spin_bonus = false

[T]
shape = [
    [[1, 0], [0, 1], [1, 1], [2, 1]],
    [[1, 0], [1, 1], [2, 1], [1, 2]],
    [[0, 1], [1, 1], [2, 1], [1, 2]],
    [[1, 0], [0, 1], [1, 1], [1, 2]],
]
color = "Magenta"
kick_table = "SRS"
spin_bonus = true

[O]
shape = [
    [[1, 0], [2, 0], [1, 1], [2, 1]],
    [[1, 0], [2, 0], [1, 1], [2, 1]],
    [[1, 0], [2, 0], [1, 1], [2, 1]],
    [[1, 0], [2, 0], [1, 1], [2, 1]],
]
color = "Yellow"
kick_table = "SRS"
spin_bonus = false

[J]
shape = [
    [[0, 0], [0, 1], [1, 1], [2, 1]],
    [[1, 0], [2, 0], [1, 1], [1, 2]],
    [[0, 1], [1, 1], [2, 1], [2, 2]],
    [[1, 0], [1, 1], [0, 2], [1, 2]],
]
color = "Blue"
kick_table = "SRS"
spin_bonus = false

[L]
shape = [
    [[2, 0], [0, 1], [1, 1], [2, 1]],
    [[1, 0], [1, 1], [1, 2], [2, 2]],
    [[0, 1], [1, 1], [2, 1], [0, 2]],
    [[0, 0], [1, 0], [1, 1], [1, 2]],
]
color = "Orange"
kick_table = "SRS"
spin_bonus = false

[S]
shape = [
    [[1, 0], [2, 0], [0, 1], [1, 1]],
    [[1, 0], [1, 1], [2, 1], [2, 2]],
    [[1, 1], [2, 1], [0, 2], [1, 2]],
    [[0, 0], [0, 1], [1, 1], [1, 2]],
]
color = "Green"
kick_table = "SRS"
spin_bonus = false

[Z]
shape = [
    [[0, 0], [1, 0], [1, 1], [2, 1]],
    [[2, 0], [1, 1], [2, 1], [1, 2]],
    [[0, 1], [1, 1], [1, 2], [2, 2]],
    [[1, 0], [0, 1], [1, 1], [0, 2]],
]
color = "Red"
kick_table = "SRS"
spin_bonus = false

[2]
shape = [
    [[1, 0], [2, 0]],
    [[2, 0], [2, 1]],
    [[1, 1], [2, 1]],
    [[1, 0], [1, 1]],
]
color = "Gray"
kick_table = "SRS"
spin_bonus = false

[X]
shape = [
    [[1, 0], [0, 1], [1, 1], [2, 1], [1, 2]],
    [[2, 0], [2, 1], [2, 2], [2, 3], [2, 4]],
    [[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]],
    [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]],
]
color = "Gray"
kick_table = "SRS_I"
spin_bonus = false

[Telescope]
shape = [
    [[1, 0], [1, 1]],
    [[1, 0], [1, 1], [1, 2]],
    [[1, 0], [1, 1], [1, 2], [1, 3]],
    [[1, 0], [1, 1], [1, 2]],
]
color = "Red"
kick_table = "Telescope"
spin_bonus = false
