# Kick tables are defining the movements that should be checked if a rotation would result in a collision.
# There is a kick list for the 3 rotations that can be made from each of the 4 rotation states.
# The kick values are [col, row] offsets that are added to the piece's position
# Up is negative and down is positive ([0, -1] checks up one row)

SRS = [
    [
        # Current State: Initial
        [[-1, 0], [-1, -1], [0, 2], [-1, 2]], # Rotate CW (Init -> CW)
        [[1, 0], [2, 0], [1, 1], [2, 1], [-1, 0], [-2, 0], [-1, 1], [-2, 1], [0,-1], [3, 0], [-3, 0]], # Rotate 180 (Init -> 180)
        [[1, 0], [1, -1], [0, 2], [1, 2]], # Rotate CCW (Init -> CCW)
    ],
    [
        # Current State: CW
        [[1, 0], [1, 1], [0, -2], [1, -2]], # Rotate CW (CW -> 180)
        [[0, 1], [0, 2], [-1, 1], [-1, 2], [0,-1], [0,-2], [-1,-1], [-1,-2], [1, 0], [0, 3], [0,-3]], # Rotate 180 (CW -> CCW)
        [[1, 0], [1, 1], [0, -2], [1, -2]], #  Rotate CCW (CW -> Init)
    ],
    [
        # Current State: 180
        [[1, 0], [1, -1], [0, 2], [1, 2]], # Rotate CW (180 -> CCW)
        [[-1, 0], [-2, 0], [-1,-1], [-2,-1], [1, 0], [2, 0], [1,-1], [2,-1], [0, 1], [-3, 0], [3, 0]], # Rotate 180 (180 -> Init)
        [[-1, 0], [-1, -1], [0, 2], [-1, 2]], # Rotate CCW (180 -> CW)
    ],
    [
        # Current State: CCW
        [[-1, 0], [-1, 1], [0, -2], [-1, -2]], # Rotate CW (CCW -> Init)
        [[0, 1], [0, 2], [1, 1], [1, 2], [0,-1], [0,-2], [1,-1], [1,-2], [-1, 0], [0, 3], [0,-3]], # Rotate 180 (CCW -> CW)
        [[-1, 0], [-1, 1], [0, -2], [-1, -2]], # Rotate CCW (CCW -> 180)
    ],
]

SRS_I = [
    [
        [[-2, 0], [1, 0], [-2, 1], [1, -2]], # Init -> CW
        [[-1, 0], [-2, 0], [1, 0], [2, 0], [0, 1]], # Init -> 180
        [[-1, 0], [2, 0], [-1, -2], [2, 1]], # Init -> CCW
    ],
    [
        [[-1, 0], [2, 0], [-1, -2], [2, 1]], # CW -> 180
        [[0, 1], [0, 2], [0,-1], [0,-2], [-1, 0]], # CW -> CCW
        [[2, 0], [-1, 0], [2, -1], [-1, 2]], # CW -> Init
    ],
    [
        [[2, 0], [-1, 0], [2, -1], [-1, 2]], # 180 -> CCW
        [[1, 0], [2, 0], [-1, 0], [-2, 0], [0,-1]], # 180 -> Init
        [[1, 0], [-2, 0], [1, 2], [-2, -1]], # 180 -> CW
    ],
    [
        [[1, 0], [-2, 0], [1, 2], [-2, -1]], # CCW -> Init
        [[0, 1], [0, 2], [0,-1], [0,-2], [1, 0]], # CCW -> CW
        [[-2, 0], [1, 0], [-2, 1], [1, -2]], # CCW -> 180
    ],
]
