[SRS]
data = [
    [
        [[-1, 0], [-1, -1], [0, 2], [-1, 2]], # Init -> CW
        [], # Init -> 180
        [[1, 0], [1, -1], [0, 2], [1, 2]], # Init -> CCW
    ],
    [
        [[1, 0], [1, 1], [0, -2], [1, -2]], # CW -> 180
        [], # CW -> CCW
        [[1, 0], [1, 1], [0, -2], [1, -2]], # CW -> Init
    ],
    [
        [[1, 0], [1, -1], [0, 2], [1, 2]], # 180 -> CCW
        [], # 180 -> Init
        [[-1, 0], [-1, -1], [0, 2], [-1, 2]], # 180 -> CW
    ],
    [
        [[-1, 0], [-1, 1], [0, -2], [-1, -2]], # CCW -> Init
        [], # CCW -> CW
        [[-1, 0], [-1, 1], [0, -2], [-1, -2]], # CCW -> 180
    ],
]

[SRS_I]
data = [
    [
        [[-2, 0], [1, 0], [-2, 1], [1, -2]], # Init -> CW
        [], # Init -> 180
        [[-1, 0], [2, 0], [-1, -2], [2, 1]], # Init -> CCW
    ],
    [
        [[-1, 0], [2, 0], [-1, -2], [2, 1]], # CW -> 180
        [], # CW -> CCW
        [[2, 0], [-1, 0], [2, -1], [-1, 2]], # CW -> Init
    ],
    [
        [[2, 0], [-1, 0], [2, -1], [-1, 2]], # 180 -> CCW
        [], # 180 -> Init
        [[1, 0], [-2, 0], [1, 2], [-2, -1]], # 180 -> CW
    ],
    [
        [[1, 0], [-2, 0], [1, 2], [-2, -1]], # CCW -> Init
        [], # CCW -> CW
        [[-2, 0], [1, 0], [-2, 1], [1, -2]], # CCW -> 180
    ],
]